// wellknown.js — generators for the two small text files a site is expected
// to publish but rarely bothers to write by hand: /robots.txt (idea #40) and
// /.well-known/security.txt (idea #41, RFC 9116).
//
// Both are generated from settings CatWAF already holds — the blocked
// user-agent list feeds robots.txt directly, so a site owner who has told
// CatWAF which crawlers they do not want does not also have to tell robots.txt.
//
// The output is served by Caddy from a generated file (see render/site.js),
// and the same functions back the dashboard's live preview, so what is
// previewed is byte-for-byte what is served.

const settings = require('./settings')
const state = require('./state')
const { stripBraces } = require('./render/util')

function sanitizeLine(value) {
  return stripBraces(String(value ?? '')).replace(/[\r\n]+/g, ' ').trim()
}

function buildRobotsTxt(opts = {}) {
  const cfg = opts.config || settings.get('robots')
  if (!cfg.enabled) return null

  const lines = ['# Generated by CatWAF — edit under Content & Headers -> robots.txt']

  const rules = []
  if (cfg.mode === 'disallow-all') {
    rules.push({ ua: '*', directive: 'Disallow', path: '/' })
  } else {
    for (const p of cfg.allow_paths) rules.push({ ua: '*', directive: 'Allow', path: p })
    for (const p of cfg.disallow_paths) rules.push({ ua: '*', directive: 'Disallow', path: p })
    if (cfg.mode === 'allow-all' && !cfg.disallow_paths.length && !cfg.allow_paths.length) {
      rules.push({ ua: '*', directive: 'Allow', path: '/' })
    }
  }

  // Group by user agent so the file reads the way a crawler expects: one
  // User-agent line followed by its own directives.
  const byUa = new Map()
  const push = (ua, directive, p) => {
    const key = sanitizeLine(ua) || '*'
    if (!byUa.has(key)) byUa.set(key, [])
    byUa.get(key).push(`${directive}: ${sanitizeLine(p) || '/'}`)
  }

  for (const r of rules) push(r.ua, r.directive, r.path)

  if (cfg.block_known_bad_bots) {
    for (const ua of (state.WAF.blocked_user_agents || [])) push(ua, 'Disallow', '/')
  }

  for (const r of cfg.extra_rules || []) push(r.user_agent, r.directive, r.path)

  // '*' first — some crawlers stop at the first matching group.
  const order = ['*', ...[...byUa.keys()].filter(k => k !== '*').sort()]
  for (const ua of order) {
    const directives = byUa.get(ua)
    if (!directives || !directives.length) continue
    lines.push('', `User-agent: ${ua}`)
    lines.push(...[...new Set(directives)])
    if (ua === '*' && cfg.crawl_delay > 0) lines.push(`Crawl-delay: ${cfg.crawl_delay}`)
  }

  if (cfg.sitemap_url) lines.push('', `Sitemap: ${sanitizeLine(cfg.sitemap_url)}`)

  return lines.join('\n') + '\n'
}

// RFC 9116 requires Contact and Expires; everything else is optional. The
// validator below is what the API and the dashboard both report against.
function validateSecurityTxt(cfg = settings.get('security_txt')) {
  const errors = []
  if (!cfg.enabled) return { ok: true, errors: [] }
  const contacts = (cfg.contact || []).map(sanitizeLine).filter(Boolean)
  if (!contacts.length) errors.push('At least one Contact value is required (RFC 9116 §2.5.3).')
  for (const c of contacts) {
    if (!/^(mailto:|https:\/\/|tel:)/.test(c)) errors.push(`Contact "${c}" must be a mailto:, https:// or tel: URI.`)
  }
  if (!cfg.expires) errors.push('Expires is required (RFC 9116 §2.5.5).')
  else {
    const when = new Date(cfg.expires.length === 10 ? `${cfg.expires}T00:00:00Z` : cfg.expires)
    if (Number.isNaN(when.getTime())) errors.push('Expires is not a valid date.')
    else if (when.getTime() < Date.now()) errors.push('Expires is in the past — the file is considered stale by researchers and scanners.')
  }
  return { ok: errors.length === 0, errors }
}

function buildSecurityTxt(opts = {}) {
  const cfg = opts.config || settings.get('security_txt')
  if (!cfg.enabled) return null
  const check = validateSecurityTxt(cfg)
  if (!check.ok && opts.strict !== false) return null

  const lines = ['# Generated by CatWAF (RFC 9116)']
  for (const c of cfg.contact) lines.push(`Contact: ${sanitizeLine(c)}`)
  if (cfg.expires) {
    const iso = cfg.expires.length === 10 ? `${cfg.expires}T00:00:00.000Z` : cfg.expires
    lines.push(`Expires: ${new Date(iso).toISOString()}`)
  }
  if (cfg.encryption) lines.push(`Encryption: ${sanitizeLine(cfg.encryption)}`)
  if (cfg.acknowledgments) lines.push(`Acknowledgments: ${sanitizeLine(cfg.acknowledgments)}`)
  if ((cfg.preferred_languages || []).length) {
    lines.push(`Preferred-Languages: ${cfg.preferred_languages.map(sanitizeLine).join(', ')}`)
  }
  if (cfg.canonical) lines.push(`Canonical: ${sanitizeLine(cfg.canonical)}`)
  if (cfg.policy) lines.push(`Policy: ${sanitizeLine(cfg.policy)}`)
  if (cfg.hiring) lines.push(`Hiring: ${sanitizeLine(cfg.hiring)}`)
  return lines.join('\n') + '\n'
}

module.exports = { buildRobotsTxt, buildSecurityTxt, validateSecurityTxt }
