// proxy/generator.js — renders the Caddyfile text for auto-discovered
// routes. Each route gets its own site block with the SAME coraza_waf
// protection as CatWAF's main managed block (backend/services/caddy.js
// buildCorazaSnippet), so a discovered app is actually protected, not just
// proxied.

const caddySvc = require('../caddy')

const AUTO_MARKER_START = '# @@CATWAF_AUTO_START@@'
const AUTO_MARKER_END = '# @@CATWAF_AUTO_END@@'

// Last gate before anything is written to a real Caddyfile. Discovery data
// originates in Docker labels, env vars and container config files — all
// attacker-controlled — so nothing is interpolated here without being
// checked, independently of the sanitising done at the discovery boundary.
//
// host:port, ipv4:port, or [ipv6]:port. Nothing else can produce a valid
// upstream, so anything else is a bug or an injection attempt.
const UPSTREAM_RE = /^(?:[A-Za-z0-9][A-Za-z0-9_.-]*|\[[0-9A-Fa-f:]+\]):\d{1,5}$/

function assertSafeUpstream(upstream) {
  if (typeof upstream !== 'string' || !UPSTREAM_RE.test(upstream)) {
    throw new Error(`Refusing to generate a route with an unsafe upstream: ${JSON.stringify(upstream)}`)
  }
  return upstream
}

function assertSafePort(port) {
  const n = Number(port)
  if (!Number.isInteger(n) || n < 1 || n > 65535) {
    throw new Error(`Refusing to generate a route with an invalid listen port: ${JSON.stringify(port)}`)
  }
  return n
}

// Comments are the one place free text appears. A newline would end the
// comment and turn the rest into live directives, so they cannot survive.
function safeComment(text, fallback = 'unknown') {
  const s = String(text ?? '').replace(/[\r\n]+/g, ' ').trim()
  return s.slice(0, 120) || fallback
}

// A discovered route gets the same protection AND the same proxy behaviour
// as the hand-configured site: WebSocket policy, upstream protocol, upstream
// TLS verification, failover tuning (ideas #26-#31, #60). Reading them from
// the shared renderer rather than duplicating the directive strings is what
// keeps the two paths from drifting.
function proxySettings() {
  try { return require('../settings').get('proxy') } catch { return null }
}

function buildRouteBlock(route, waf) {
  const lines = []
  const port = assertSafePort(route.listenPort)
  const upstream = assertSafeUpstream(route.upstream)
  const proxy = proxySettings()

  lines.push(`:${port} {`)

  if (proxy && proxy.websockets === 'deny') {
    lines.push('    @catwaf_websocket header Connection *Upgrade*')
    lines.push('    respond @catwaf_websocket 403')
  }

  const target = proxy && proxy.protocol === 'grpc' && !/^[a-z0-9]+:\/\//.test(upstream)
    ? `h2c://${upstream}`
    : upstream

  let options = []
  if (proxy) {
    try { options = require('../render/site').proxyOptions(proxy) } catch { options = [] }
  }

  if (options.length) {
    lines.push(`    reverse_proxy ${target} {`)
    for (const option of options) lines.push(`        ${option}`)
    lines.push('    }')
  } else {
    lines.push(`    reverse_proxy ${target}`)
  }

  lines.push('')
  lines.push(caddySvc.buildCorazaSnippet(waf))
  lines.push('}')
  return lines.join('\n')
}

// Returns null when there is nothing to write (no routes) so callers can
// tell "generated an empty region" apart from "nothing changed".
function buildAutoRegion(routes, waf) {
  if (!routes.length) return null
  const lines = []
  lines.push(AUTO_MARKER_START)
  lines.push('# CatWAF Auto — reverse-proxy routes for auto-discovered apps.')
  lines.push('# Generated by `catwaf auto`. Safe to remove manually if unwanted;')
  lines.push('# re-running `catwaf auto` regenerates this whole region from scratch.')
  lines.push('')
  for (const route of routes) {
    lines.push(`# ${safeComment(route.name)} (${safeComment(route.runtime, 'unknown runtime')}) — container ${safeComment(route.containerName)}`)
    lines.push(buildRouteBlock(route, waf))
    lines.push('')
  }
  lines.push(AUTO_MARKER_END)
  return lines.join('\n')
}

module.exports = {
  buildAutoRegion, buildRouteBlock, safeComment,
  assertSafeUpstream, assertSafePort,
  AUTO_MARKER_START, AUTO_MARKER_END,
}
